In [1]:
import numpy as np 

def GE( U , b ) : 
    '''
    Param U: nxn matrix of the coefficients. ( Upper Trangular ) 
    Param b: nx1 matrix of the constants in the equation. 
    '''
    if( type( U ) == list ):
        U = np.array( U , dtype = float  ) 
    if( type( b ) == list ) :
        b = np.array( b , dtype = float )

    n = U.shape[0] 
    
    if( n != U.shape[1] ) : 
        raise ValueError('U must be a square matrix') 
    if( n != b.shape[0] ) : 
        raise ValueError('Dimentions of U and b do not match' ) 
    
    b = b.reshape( ( n, -1 ) ) 
    U = np.concatenate( ( U , b ) , axis = 1  )

    for i in range( n - 1 ) : 
        for j in range( i + 1 , n ) : 
            U[j,:] -= ( U[j,i]/U[i,i] )*U[i,:] 

    return U[: , :n ] , U[: , -1 ] 


In [2]:
# back substitution 

def BackSt( U , b ): 
    '''
    Param U: nxn matrix of the coefficients. ( Upper Trangular ) 
    Param b: nx1 matrix of the constants in the equation. 
    '''
    if( type( U ) == list ) :
        U = np.array( U , dtype = float  ) 
    if( type( b ) == list ) :
        b = np.array( b , dtype = float )

    n = U.shape[0] 
    
    if( n != U.shape[1] ) : 
        raise ValueError('U must be a square matrix') 
    if( n != b.shape[0] ) : 
        raise ValueError('Dimentions of U and b do not match' ) 

    x = np.zeros( n )
    
    x[n-1] = b[n-1]/U[ n -1 , n -1 ] 

    for i in range( n -2 , -1 , -1 ) : 
        temp = .0 
        for j in range( i + 1 , n ) : 
            temp += x[j]*U[i,j]
        x[i] = ( b[i] - temp )/U[i,i] 
    
    return x 

In [3]:
def GEPP( U , b ) : 
    '''
    Param U: nxn matrix of the coefficients. ( Upper Trangular ) 
    Param b: nx1 matrix of the constants in the equation. 
    '''
    
    if( type( U ) == list ):
        U = np.array( U , dtype = float  ) 
    if( type( b ) == list ) :
        b = np.array( b , dtype = float )

    n = U.shape[0] 

    # define the pivot list : 
    p = np.arange( n ) 
    
    if( n != U.shape[1] ) : 
        raise ValueError('U must be a square matrix') 
    if( n != b.shape[0] ) : 
        raise ValueError('Dimentions of U and b do not match' ) 
    
    b = b.reshape( ( n, -1 ) ) 
    U = np.concatenate( ( U , b ) , axis = 1  )

    for i in range(  n -1 ) : 
        # find the max element from the row elements bellow :
        m = i 
        for j in range( i + 1 , n  ) : 
            if  abs( U[p[m],i] ) < abs( U[p[j],i]) : 
                m = j 
        # swich the rows 
        l = p[i] 
        p[i] = p[m] 
        p[m] = l 

        # apply a step of GE : 
        for j in range( i + 1 , n ) : 
            U[p[j],:] -= ( U[p[j],i]/U[p[i],i] )*U[p[i],:] 
        
    return U[: , :n ] , U[: , -1 ] , p  


In [4]:
# back substitution with partial pivoting ! 

def BackStPP( U , b , p ): 
    '''
    Param U: nxn matrix of the coefficients. ( Upper Trangular ) 
    Param b: nx1 matrix of the constants in the equation. 
    '''
    if( type( U ) == list ) :
        U = np.array( U , dtype = float  ) 
    if( type( b ) == list ) :
        b = np.array( b , dtype = float )
    if type( p ) == list : 
        p = np.array( p ) 

    n = U.shape[0] 
    
    if( n != U.shape[1] ) : 
        raise ValueError('U must be a square matrix') 
    if( n != b.shape[0] ) : 
        raise ValueError('Dimentions of U and b do not match' ) 
    if( n != p.shape[0] ) : 
        raise ValueError('Dimentions of p and U do not match' ) 
    
    x = np.zeros( n )
    
    x[n-1] = b[p[n-1]]/U[ p[n-1] , n-1 ] 

    for i in range( n -2 , -1 , -1 ) : 
        temp = .0 
        for j in range( i + 1 , n ) : 
            temp += x[j]*U[p[i],j]
        x[i] = ( b[p[i]] - temp )/U[p[i],i] 
    
    return x 

In [5]:
# determinant with partial pivoting : 
def detPP( U ) : 
    '''
    Param U: nxn matrix of the coefficients. ( Upper Trangular ) 
    '''
    
    if( type( U ) == list ):
        U = np.array( U , dtype = float  ) 

    n = U.shape[0] 

    # define the pivot list : 
    p = np.arange( n ) 
    
    if( n != U.shape[1] ) : 
        raise ValueError('U must be a square matrix') 

    for i in range(  n -1 ) : 
        # find the max element from the row elements bellow :
        m = i 
        for j in range( i + 1 , n  ) : 
            if  abs( U[p[m],i] ) < abs( U[p[j],i]) : 
                m = j 
        # swich the rows 
        l = p[i] 
        p[i] = p[m] 
        p[m] = l 

        # apply a step of GE : 
        for j in range( i + 1 , n ) : 
            U[p[j],:] -= ( U[p[j],i]/U[p[i],i] )*U[p[i],:] 
        
    temp = 1 
    for i in range(n): 
        temp *= U[p[i],i]
    
    return temp 

In [6]:
U = np.array( [ [ 1 , 2 , 4  ] , 
               [ 3 , 4  , 8 ] , 
              [ 2, 4 , 12] ]  , dtype = float ) 
b = np.array( [ 2 , 7, 12 ]  , dtype = float )


In [7]:
detPP( U )

-8.0

In [8]:
U 

array([[ 0.        ,  0.        , -2.        ],
       [ 3.        ,  4.        ,  8.        ],
       [ 0.        ,  1.33333333,  6.66666667]])

In [9]:
b

array([ 2.,  7., 12.])

In [10]:
b = b.reshape( ( 3 ,1  ))
b 

array([[ 2.],
       [ 7.],
       [12.]])

In [11]:
np.concatenate( ( U , b ) , axis = 1 )

array([[ 0.        ,  0.        , -2.        ,  2.        ],
       [ 3.        ,  4.        ,  8.        ,  7.        ],
       [ 0.        ,  1.33333333,  6.66666667, 12.        ]])

In [12]:
U 

array([[ 0.        ,  0.        , -2.        ],
       [ 3.        ,  4.        ,  8.        ],
       [ 0.        ,  1.33333333,  6.66666667]])

In [13]:
U1 , b1 = GE( U , b ) 
U2, b2 , p = GEPP( U , b ) 

/var/folders/kb/nnzj_yrn3n7cy09fy5x_kcsc0000gn/T/ipykernel_20192/1431520095.py:25: RuntimeWarning: divide by zero encountered in scalar divide
  U[j,:] -= ( U[j,i]/U[i,i] )*U[i,:]
/var/folders/kb/nnzj_yrn3n7cy09fy5x_kcsc0000gn/T/ipykernel_20192/1431520095.py:25: RuntimeWarning: invalid value encountered in multiply
  U[j,:] -= ( U[j,i]/U[i,i] )*U[i,:]
/var/folders/kb/nnzj_yrn3n7cy09fy5x_kcsc0000gn/T/ipykernel_20192/1431520095.py:25: RuntimeWarning: invalid value encountered in scalar divide
  U[j,:] -= ( U[j,i]/U[i,i] )*U[i,:]


In [14]:
U1

array([[ 0.,  0., -2.],
       [nan, nan, inf],
       [nan, nan, nan]])

In [15]:
b1

array([  2., -inf,  nan])

In [16]:
U2

array([[ 0.        ,  0.        , -2.        ],
       [ 3.        ,  4.        ,  8.        ],
       [ 0.        ,  1.33333333,  6.66666667]])

In [17]:
b2

array([ 2.,  7., 12.])

In [18]:
p

array([1, 2, 0])

In [19]:
x = BackSt( U1 , b1 ) 
x 

array([nan, nan, nan])

In [20]:
x2 = BackStPP( U2 , b2 , p )
x2  

array([-13.66666667,  14.        ,  -1.        ])

In [21]:
U = [
    [ 12 , 10 , -7 ] , 
    [ 6 , 5 , 3 ] , 
    [ 5 , -1 , 5 ] 
]

b = [ 15 , 14 , 9 ] 

In [22]:
U1, b1 = GE( U , b ) 
U1 , b1 

/var/folders/kb/nnzj_yrn3n7cy09fy5x_kcsc0000gn/T/ipykernel_20192/1431520095.py:25: RuntimeWarning: divide by zero encountered in scalar divide
  U[j,:] -= ( U[j,i]/U[i,i] )*U[i,:]
/var/folders/kb/nnzj_yrn3n7cy09fy5x_kcsc0000gn/T/ipykernel_20192/1431520095.py:25: RuntimeWarning: invalid value encountered in multiply
  U[j,:] -= ( U[j,i]/U[i,i] )*U[i,:]


(array([[12. , 10. , -7. ],
        [ 0. ,  0. ,  6.5],
        [ nan,  nan,  inf]]),
 array([15. ,  6.5,  inf]))

In [23]:
U1 , b1 , p = GEPP( U , b ) 
U1 , b1 , p 

(array([[12.        , 10.        , -7.        ],
        [ 0.        ,  0.        ,  6.5       ],
        [ 0.        , -5.16666667,  7.91666667]]),
 array([15.  ,  6.5 ,  2.75]),
 array([0, 2, 1]))

In [24]:
x = BackStPP( U1 , b1 , p ) 
x 

array([1., 1., 1.])