## LU - Factorization 

In [1]:
import numpy as np 

In [2]:
def LUfactor(A): 
    n = A.shape[0]

    if A.shape[1] != n : 
        raise ValueError('A must be a Square Matrix')
    
    L = np.eye( n )
    U = np.zeros((n,n))
    
    for k in range(n-1) : 
        
        # kth row of U : 
        for j in range(k,n): 
            # print( A[k,j] , np.sum(L[k , :k]*U[:k,j]) )
            U[k,j] = A[k,j] - np.sum(L[k , :k]*U[:k,j])
        
        # print(f'----{k}th iteration ------ \n {U} \n {L}')
        
        # print( U , '\n' , L )
        if( k < n-1 and U[k,k] == 0 ): 
            print('Error : Zero Encountered in Diagonal Element of U ')
            return L , U 
        
        # kth column of L : 
        for j in range(k+1,n): 
            L[j,k] = ( A[j,k] - np.sum(L[j,:k]*U[:k,k]) )/U[k,k]
        
    return L , U  

In [3]:
A = np.array([
    [2,3,1],
    [4,5,2], 
    [6,7,3]
])

L , U  = LUfactor( A )
np.matmul( L , U )

array([[2., 3., 1.],
       [4., 5., 2.],
       [6., 7., 3.]])

In [4]:
np.linalg.det( A )

4.440892098500646e-16

In [5]:
A = np.array([
    [1,2,1,3],
    [2,4,1,5],
    [3,2,1,4],
    [4,1,1,3]
])

print( np.linalg.det(A) )

L , U  = LUfactor( A )
np.matmul( L , U )

3.000000000000002
Error : Zero Encountered in Diagonal Element of U 


array([[ 1.,  2.,  1.,  3.],
       [ 2.,  4.,  1.,  5.],
       [ 3.,  6.,  3.,  9.],
       [ 4.,  8.,  4., 12.]])

In [6]:
A = np.array([
    [5,0,0],
    [0,7,0],
    [0,0,9]
])

print( np.linalg.det(A) )

L , U  = LUfactor( A )
print( L , '\n' , U )
np.matmul( L , U )

315.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 [[5. 0. 0.]
 [0. 7. 0.]
 [0. 0. 0.]]


array([[5., 0., 0.],
       [0., 7., 0.],
       [0., 0., 0.]])

In [7]:
A = np.array([
    [2,0,1],
    [4,3,2],
    [6,0,5]
])

print( np.linalg.det(A) )

L , U  = LUfactor( A )
print( L , '\n' , U )
np.matmul( L , U )

11.999999999999995
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 0. 1.]] 
 [[2. 0. 1.]
 [0. 3. 0.]
 [0. 0. 0.]]


array([[2., 0., 1.],
       [4., 3., 2.],
       [6., 0., 3.]])